In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

Iris=pd.read_csv("Iris (1).csv")

In [5]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


# KNN

In [9]:
Iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [12]:
X=Iris.drop("Species",axis=1)
y=Iris["Species"]

In [13]:
print(X.head())
print(y.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
scaler = StandardScaler()
x_train_scaler=scaler.fit_transform(X_train)
x_test_scaled=scaler.transform(X_test)

In [29]:
KNN= KNeighborsClassifier(n_neighbors= 3)
KNN.fit(x_train_scaler,y_train)


,n_neighbors,3
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [30]:
y_pred=KNN.predict(x_test_scaled)

In [36]:
from sklearn.metrics import precision_score,accuracy_score,recall_score,f1_score

print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))






accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


In [37]:
KNN= KNeighborsClassifier(n_neighbors= 5)
KNN.fit(x_train_scaler,y_train)
y_pred=KNN.predict(x_test_scaled)
from sklearn.metrics import precision_score,accuracy_score,recall_score,f1_score

print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))


accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


In [38]:
KNN= KNeighborsClassifier(n_neighbors= 7)
KNN.fit(x_train_scaler,y_train)
y_pred=KNN.predict(x_test_scaled)
from sklearn.metrics import precision_score,accuracy_score,recall_score,f1_score

print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))


accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


# overfitting


In [40]:
train_score = KNN.score(x_train_scaler,y_train)

test_score = KNN.score(x_test_scaled,y_test)

print("Training Accuracy :",train_score)
print("Testing Accuracy :",test_score)

Training Accuracy : 0.9916666666666667
Testing Accuracy : 1.0


In [41]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [42]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(KNN,X,y,cv=5)

print(scores)
print(scores.mean())

[0.66666667 1.         1.         1.         0.66666667]
0.8666666666666666


In [44]:
for i in range(1,15):

    knn = KNeighborsClassifier(n_neighbors=i)

    scores = cross_val_score(knn,X,y,cv=5)

    print(i,scores.mean())

1 0.8733333333333333
2 0.8799999999999999
3 0.8733333333333333
4 0.8799999999999999
5 0.8733333333333333
6 0.8799999999999999
7 0.8666666666666666
8 0.8799999999999999
9 0.8666666666666666
10 0.8799999999999999
11 0.8666666666666666
12 0.8799999999999999
13 0.8666666666666666
14 0.8799999999999999


# Naive Bayes

In [45]:
from sklearn.naive_bayes import GaussianNB

In [46]:
gnb_model = GaussianNB()
gnb_model.fit(X_train,y_train)

,priors,None
,var_smoothing,1e-09


In [47]:
y_predgnb_model.predict(X_test)

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype='<U15')

In [49]:
print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))


accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


# LogisticRegression

In [50]:
from sklearn.linear_model import LogisticRegression

In [53]:
Log_model=LogisticRegression(max_iter=1000)

In [54]:
Log_model.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [55]:
Log_model.predict(X_test)

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [56]:
print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))


accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


In [63]:
Log_model=LogisticRegression(max_iter=1000)
Log_model.fit(x_train_scaler,y_train)
Log_model.predict(x_test_scaled)
print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))
print("f1_score",f1_score(y_test,y_pred,average='weighted'))


accuracy_score 1.0
precision_score 1.0
recall_score 1.0
f1_score 1.0


In [66]:
print("cm:", confusion_matrix(y_test, y_pred))
print("classification report:", classification_report(y_test, y_pred))

cm: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
classification report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

